In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df=pd.read_csv('dataset/processed/train.csv')
df.head()

,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Datetime
0,"""CNR4352144""",Completed,"""CID8362794""",Bike,Udyog Vihar,Ambience Mall,10.8,38.9,NaN,NaN,NaN,NaN,NaN,NaN,99.0,37.98,4.8,4.8,Cash,2024-01-01 00:19:34
1,"""CNR9147645""",Completed,"""CID8300238""",Go Mini,Basai Dhankot,Madipur,8.5,15.1,NaN,NaN,NaN,NaN,NaN,NaN,114.0,39.29,4.2,4.1,Uber Wallet,2024-01-01 01:35:18
2,"""CNR1009222""",Cancelled by Driver,"""CID2030746""",Go Sedan,Tughlakabad,Greater Kailash,7.4,NaN,NaN,NaN,1.0,More than permitted people in there,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01 01:37:50
3,"""CNR2740479""",Cancelled by Driver,"""CID3231181""",Auto,Palam Vihar,Kherki Daula Toll,5.6,NaN,NaN,NaN,1.0,Personal & Car related issues,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01 01:48:03
4,"""CNR7650148""",Cancelled by Driver,"""CID3381661""",Go Sedan,Narsinghpur,Pulbangash,6.2,NaN,NaN,NaN,1.0,More than permitted people in there,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-01 01:49:56

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Booking ID                         100000 non-null  str
 1   Booking Status                     100000 non-null  str
 2   Customer ID                        100000 non-null  str
 3   Vehicle Type                       100000 non-null  str
 4   Pickup Location                    100000 non-null  str
 5   Drop Location                      100000 non-null  str
 6   Avg VTAT                           92999 non-null   float64
 7   Avg CTAT                           67943 non-null   float64
 8   Cancelled Rides by Customer        6955 non-null    float64
 9   Reason for cancelling by Customer  6955 non-null    str
 10  Cancelled Rides by Driver          18101 non-null   float64
 11  Driver Cancellation Reason         18101 non-null   str
 12  Incomplete Rides                   5961 non-null    float64
 13  Incomplete Rides Reason            5961 non-null    str
 14  Booking Value                      67943 non-null   float64
 15  Ride Distance                      67943 non-null   float64
 16  Driver Ratings                     61982 non-null   float64
 17  Customer Rating                    61982 non-null   float64
 18  Payment Method                     67943 non-null   str
 19  Datetime                           100000 non-null  str
dtypes: float64(9), str(11)
memory usage: 15.3 MB

In [17]:
df['Datetime'] = pd.to_datetime(df['Datetime'])

cols = ['Datetime'] + [col for col in df.columns if col != 'Datetime']
df = df[cols]
df.sample(5)

,Datetime,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
85706,2024-07-26 19:05:33,"""CNR3504598""",Completed,"""CID2781801""",Auto,Rajouri Garden,Sushant Lok,6.3,17.3,NaN,NaN,NaN,NaN,NaN,NaN,424.0,46.83,4.3,4.4,UPI
78452,2024-07-09 10:01:11,"""CNR9069664""",Completed,"""CID3486184""",Go Mini,Rohini West,Inderlok,7.0,37.8,NaN,NaN,NaN,NaN,NaN,NaN,922.0,34.00,4.7,4.8,Credit Card
99317,2024-08-29 11:00:29,"""CNR2772977""",Completed,"""CID6921726""",Go Sedan,Seelampur,Indraprastha,8.5,22.8,NaN,NaN,NaN,NaN,NaN,NaN,375.0,2.50,4.2,5.0,Debit Card
90092,2024-08-06 12:40:23,"""CNR1677739""",Cancelled by Driver,"""CID2923548""",Auto,Rajiv Nagar,Gurgaon Sector 56,3.8,NaN,NaN,NaN,1.0,The customer was coughing/sick,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8135,2024-01-20 17:30:58,"""CNR3300822""",Cancelled by Customer,"""CID7464516""",Bike,Badshahpur,Subhash Chowk,14.7,NaN,1.0,Driver is not moving towards pickup location,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Datetime                           100000 non-null  datetime64[us]
 1   Booking ID                         100000 non-null  str
 2   Booking Status                     100000 non-null  str
 3   Customer ID                        100000 non-null  str
 4   Vehicle Type                       100000 non-null  str
 5   Pickup Location                    100000 non-null  str
 6   Drop Location                      100000 non-null  str
 7   Avg VTAT                           92999 non-null   float64
 8   Avg CTAT                           67943 non-null   float64
 9   Cancelled Rides by Customer        6955 non-null    float64
 10  Reason for cancelling by Customer  6955 non-null    str
 11  Cancelled Rides by Driver          18101 non-null   float64
 12  Driver Cancellation Reason         18101 non-null   str
 13  Incomplete Rides                   5961 non-null    float64
 14  Incomplete Rides Reason            5961 non-null    str
 15  Booking Value                      67943 non-null   float64
 16  Ride Distance                      67943 non-null   float64
 17  Driver Ratings                     61982 non-null   float64
 18  Customer Rating                    61982 non-null   float64
 19  Payment Method                     67943 non-null   str
dtypes: datetime64[us](1), float64(9), str(10)
memory usage: 15.3 MB